"use strict";

// Short labels for the codes shown as chips in the diagnostic summary (Data & diagnostics tab). The logs and
// exports keep the raw codes; a chip shows the label and keeps the code in its tooltip. A code missing here is
// shown as is. Both languages have the same codes (a test checks it).
const DIAGNOSTIC_CODE_LABELS = {
    "zh-CN": {
        // Reason codes
        "discovered": "发现消息",
        "not-eligible-language": "不需要翻译的语言",
        "prefetch-disabled": "预翻译已关闭",
        "layout-unstable-prefetch": "页面未稳定，暂缓预翻译",
        "google-prefetch-disabled": "Google 不用于预翻译",
        "current-translation-present": "已有译文",
        "recent-render-present": "刚刚画过",
        "cache-hit": "缓存命中",
        "text-cache-hit": "文本缓存命中",
        "invalid-cache": "缓存无效",
        "dedupe-active": "同一条正在翻译",
        "terminal-failure": "多次失败后停止",
        "retry-cooldown": "等待重试",
        "api-work-blocked": "请求被暂停",
        "config-missing": "缺少配置",
        "batch-limit": "批次已满",
        "queue-limit": "队列已满",
        "enqueued": "进入队列",
        "requeued": "重新排队",
        "provider-cooldown": "服务冷却中",
        "local-provider-health": "检查本地服务",
        "prefetch-slot": "预翻译名额已满",
        "request-started": "请求开始",
        "output-received": "收到结果",
        "output-invalid": "结果不合格",
        "retrying": "重试中",
        "rendered": "已显示",
        "render-deferred": "稍后显示",
        "render-disconnected": "消息已离开页面",
        "render-text-changed": "原文已改变",
        "render-identity-changed": "消息已变化",
        "render-request-stale": "请求已过时",
        "render-outside-viewport": "不在屏幕内",
        "manual-line-present": "已有手动译文",
        "failure": "失败",
        "stale-dom": "页面已变化",
        "local-unavailable": "本地服务不可用",
        "request-success": "请求成功",
        "request-error": "请求出错",
        "request-dedupe": "合并相同请求",
        "missing-api": "缺少 API 配置",
        "missing-config": "缺少配置",
        "cache-set": "写入缓存",
        "cache-miss": "缓存未命中",
        "cache-expired": "缓存过期",
        "cache-delete": "删除缓存",
        "cache-persist": "保存缓存",
        "cache-persist-error": "保存缓存出错",
        "auto-disabled": "自动翻译已关闭",
        "route-change": "切换了频道",
        "cooldown-expired": "冷却结束",
        "viewport-settling": "等待页面稳定",
        "write-cancelled": "写入已取消",
        "write-failed": "写入失败",
        "disabled": "已关闭",
        "empty": "空内容",
        // Message states
        "skipped": "跳过",
        "cacheHit": "缓存命中",
        "queuedVisible": "排队（屏幕内）",
        "queuedPrefetch": "排队（预翻译）",
        "queuedLongText": "排队（长消息）",
        "inFlight": "翻译中",
        "validating": "检查结果",
        "cached": "已缓存",
        "failed": "失败",
        "stale": "已过时",
        "cancelled": "已取消",
        // Queues
        "manual": "手动",
        "visible": "屏幕内",
        "longText": "长消息",
        "prefetch": "预翻译",
        "history": "历史补翻",
        "queueLength": "排队",
        "inFlightItems": "进行中的消息",
        "prefetchInFlight": "预翻译进行中",
        "pendingTargets": "等待显示",
        // Flows
        "auto": "自动翻译",
        "cache": "缓存",
        "model": "模型请求",
        "polish": "润色",
        "public-bilingual": "公开双语",
        "quick-settings": "快捷设置",
        // Failure classes
        "source-incomplete": "原文不完整",
        "whole-pass-failed": "整段翻译失败",
        "chunk-failed": "分段失败",
        "subchunk-failed": "小段失败",
        "validator-rejected": "结果被拒绝",
        "render-blocked": "无法显示",
        "cache-identity-mismatch": "缓存对不上",
        "provider-output-bad": "服务返回异常",
        // Failure layers and flow stages
        "source": "读取原文",
        "plan": "拆分",
        "queue": "排队",
        "request": "请求",
        "output": "结果",
        "validation": "检查",
        "render": "显示"
    },
    en: {
        // Reason codes
        "discovered": "Found",
        "not-eligible-language": "Language not translated",
        "prefetch-disabled": "Prefetch off",
        "layout-unstable-prefetch": "Prefetch waits for page",
        "google-prefetch-disabled": "Google skips prefetch",
        "current-translation-present": "Already translated",
        "recent-render-present": "Just drawn",
        "cache-hit": "Cache hit",
        "text-cache-hit": "Text cache hit",
        "invalid-cache": "Cache invalid",
        "dedupe-active": "Already translating",
        "terminal-failure": "Stopped after failures",
        "retry-cooldown": "Waiting to retry",
        "api-work-blocked": "Requests paused",
        "config-missing": "Settings missing",
        "batch-limit": "Batch full",
        "queue-limit": "Queue full",
        "enqueued": "Queued",
        "requeued": "Queued again",
        "provider-cooldown": "Service cooling down",
        "local-provider-health": "Checking local server",
        "prefetch-slot": "Prefetch slots full",
        "request-started": "Request started",
        "output-received": "Result received",
        "output-invalid": "Result rejected",
        "retrying": "Retrying",
        "rendered": "Shown",
        "render-deferred": "Shown later",
        "render-disconnected": "Message left the page",
        "render-text-changed": "Original changed",
        "render-identity-changed": "Message changed",
        "render-request-stale": "Request outdated",
        "render-outside-viewport": "Off screen",
        "manual-line-present": "Manual translation shown",
        "failure": "Failed",
        "stale-dom": "Page changed",
        "local-unavailable": "Local server unavailable",
        "request-success": "Request OK",
        "request-error": "Request error",
        "request-dedupe": "Same request merged",
        "missing-api": "API settings missing",
        "missing-config": "Settings missing",
        "cache-set": "Cached",
        "cache-miss": "Cache miss",
        "cache-expired": "Cache expired",
        "cache-delete": "Cache deleted",
        "cache-persist": "Cache saved",
        "cache-persist-error": "Cache save error",
        "auto-disabled": "Auto-translate off",
        "route-change": "Channel changed",
        "cooldown-expired": "Cooldown over",
        "viewport-settling": "Page settling",
        "write-cancelled": "Write cancelled",
        "write-failed": "Write failed",
        "disabled": "Off",
        "empty": "Empty",
        // Message states
        "skipped": "Skipped",
        "cacheHit": "Cache hit",
        "queuedVisible": "Queued (on screen)",
        "queuedPrefetch": "Queued (prefetch)",
        "queuedLongText": "Queued (long message)",
        "inFlight": "Translating",
        "validating": "Checking result",
        "cached": "Cached",
        "failed": "Failed",
        "stale": "Outdated",
        "cancelled": "Cancelled",
        // Queues
        "manual": "Manual",
        "visible": "On screen",
        "longText": "Long messages",
        "prefetch": "Prefetch",
        "history": "History backfill",
        "queueLength": "Queued",
        "inFlightItems": "Messages in progress",
        "prefetchInFlight": "Prefetch in progress",
        "pendingTargets": "Waiting to show",
        // Flows
        "auto": "Auto-translate",
        "cache": "Cache",
        "model": "Model requests",
        "polish": "Polish",
        "public-bilingual": "Public bilingual",
        "quick-settings": "Quick settings",
        // Failure classes
        "source-incomplete": "Original incomplete",
        "whole-pass-failed": "Whole message failed",
        "chunk-failed": "Part failed",
        "subchunk-failed": "Small part failed",
        "validator-rejected": "Result rejected",
        "render-blocked": "Could not show",
        "cache-identity-mismatch": "Cache mismatch",
        "provider-output-bad": "Bad service output",
        // Failure layers and flow stages
        "source": "Reading original",
        "plan": "Splitting",
        "queue": "Queue",
        "request": "Request",
        "output": "Result",
        "validation": "Checking",
        "render": "Showing"
    }
};

function getDiagnosticCodeLabel(code, locale = "zh-CN") {
    const value = String(code ?? "");
    const table = DIAGNOSTIC_CODE_LABELS[locale] || DIAGNOSTIC_CODE_LABELS.en;
    return Object.prototype.hasOwnProperty.call(table, value) ? table[value] : value;
}

module.exports = { DIAGNOSTIC_CODE_LABELS, getDiagnosticCodeLabel };
