"use strict";

const fs = require("node:fs");
const path = require("node:path");
const esbuild = require("esbuild");

const root = path.resolve(__dirname, "..");
const entry = path.join(root, "src", "index.js");
const metadataPath = path.join(root, "src", "metadata.txt");
const outputPath = path.join(root, "DiscordAITranslator.plugin.js");
const packageJson = require(path.join(root, "package.json"));
const checkOnly = process.argv.includes("--check");

function normalizeLf(value) {
    return String(value || "").replace(/\r\n?/g, "\n");
}

async function createArtifact() {
    const metadata = normalizeLf(fs.readFileSync(metadataPath, "utf8")).trimEnd();
    const result = await esbuild.build({
        entryPoints: [entry],
        outfile: outputPath,
        bundle: true,
        write: false,
        format: "cjs",
        platform: "node",
        target: "node20",
        charset: "utf8",
        legalComments: "none",
        treeShaking: false,
        minify: false,
        sourcemap: false,
        logLevel: "silent",
        banner: {
            js: `${metadata}\n// Generated from src/index.js. Run npm run build; do not edit this file directly.`
        }
    });
    const artifact = result.outputFiles?.[0]?.contents;
    if (!artifact?.length) throw new Error("esbuild produced an empty plugin artifact.");
    return Buffer.from(artifact);
}

function assertArtifactShape(artifact) {
    const text = artifact.toString("utf8");
    if (!text.startsWith("/**\n * @name DiscordAITranslator")) {
        throw new Error("Generated plugin metadata is not at byte 0.");
    }
    const metadataVersion = text.match(/@version\s+([^\s]+)/)?.[1] || "";
    if (metadataVersion !== packageJson.version) {
        throw new Error(`Generated plugin metadata version does not match package version ${packageJson.version}.`);
    }
}

async function main() {
    const artifact = await createArtifact();
    assertArtifactShape(artifact);
    if (checkOnly) {
        if (!fs.existsSync(outputPath)) throw new Error("Generated plugin is missing. Run npm run build.");
        const current = fs.readFileSync(outputPath);
        if (!current.equals(artifact)) throw new Error("Generated plugin is stale. Run npm run build and commit the result.");
        process.stdout.write("Generated plugin is up to date.\n");
        return;
    }
    fs.writeFileSync(outputPath, artifact);
    delete require.cache[require.resolve(outputPath)];
    const Plugin = require(outputPath);
    if (typeof Plugin !== "function") throw new Error("Generated plugin must export the BetterDiscord plugin class.");
    process.stdout.write(`Built ${path.basename(outputPath)} (${artifact.length} bytes).\n`);
}

main().catch(error => {
    console.error(error?.stack || error);
    process.exit(1);
});
